### ISSUE TITLE
i can't find Netflow accounting mechanism implementation in your codes

### ISSUE THREAD

**Issue by seyedsalar** [Tribler/trustchain-superapp#49]
hi thanks for your very useful and perfect project, i am working on this project but can't find where that trust scores calculation. please help me. what module or section do that?

**Comment by devos50** [comment]
Hi! Thanks for your interest in the NetFlow accounting mechanism.

Unfortunately, NetFlow is currently not integrated in any of our software. We used to have an implementation in [Tribler](https://github.com/tribler/tribler) but we did remove that a long time ago, since it was computationally expensive and mostly unused. We are currently designing/implementing a new reputation mechanism.

Please let me know if you have any other questions!

**Comment by seyedsalar** [comment]
Thanks for your reply, my research is about accounting mechanism too 🙂🙂

**Comment by devos50** [comment]
Sounds good! Besides TrustChain (and an improved version of TrustChain which is accepted in [this workshop](https://dicg2020.github.io)), I've been mostly working on blockchain-based electronic marketplaces. Another PhD student in our lab, @grimadas, is currently focussing on accounting mechanisms. As part of our research efforts, we are currently building an "ultimate" accounting mechanism, which ongoing implementation can be found [here](https://github.com/tribler/bami). Given your research scope, this might be interesting 👍

**Comment by seyedsalar** [comment]
Thanks for your very useful comments dear friend, is any paper for BAMI protocol?

**Comment by devos50** [comment]
We had a prior paper submission about the BAMI protocol but it got rejected unfortunately. We plan on rewriting this work something soon. 👍

**Comment by seyedsalar** [comment]
I'm sure it will accept very soon👍👍your team is very active.
